Changes required to compile and run cuda kernels
microsoft/hat pull request #53
Opened 2022-05-13 22:15 UTC by ritwikdas

- Added cuda compiler arguments and header directory
- removed dependency from pynvrtc
- removed streams

2022-05-13 22:26 UTC, kernhanda requested changes

2022-05-13 22:26 UTC, kernhanda commented on hatlib/cuda_loader.py
>  def device_args_to_ptr_list(device_args: List):
undo the removal of stream -- i understand that the code isn't being used right now, but it works and i'd rather not go through adding them back again when we do need them.

2022-05-13 22:26 UTC, kernhanda commented on hatlib/cuda_loader.py
> +        b'--include-path=/usr/local/cuda-11.6/targets/x86_64-linux/include/',
we should use either `/usr/local/cuda/` or `/usr/local/cuda-11/` (which are symlinks to the real installation. there are environment variables that can be used as well.

2022-05-13 22:26 UTC, kernhanda commented on hatlib/cuda_loader.py
> +    # ptx = prog.compile(opts)
remove commented out code

2022-05-13 22:26 UTC, kernhanda commented on hatlib/cuda_loader.py
>  def compile_cuda_program(cuda_src_path: pathlib.Path, func_name):
func_name is no longer used in this function

2022-05-13 22:41 UTC, ritwikdas commented on hatlib/cuda_loader.py
>  def device_args_to_ptr_list(device_args: List):
1. Can you give me 1 good reason why streams can be useful here?
2. You have yourself removed the usage of streams from the ROCM loader in a previous commit, do the rocm runner and the cuda runner have different use cases? If not, what are you talking about here?? ("Removes the usage of streams for kernel launches.")(https://github.com/microsoft/hat/commit/397334322dd75c24aac799361543768dc09710d3)

2022-05-13 22:47 UTC, ritwikdas commented on hatlib/cuda_loader.py
>  def compile_cuda_program(cuda_src_path: pathlib.Path, func_name):
how can you create a cuda program without a function name? :) see line 57

2022-05-17 03:23 UTC, ritwikdas commented on hatlib/cuda_loader.py
>  def device_args_to_ptr_list(device_args: List):
Closing this as non-actionable since firstly this is not a good idea and secondly because I didn't get any response on the clarifications mentioned above.

P.S.: Just because someone on the internet used streams does not necessarily make it useful for us. We should try to keep the code as lean, clean and robust as possible. The simplicity will benefit us if/when we debug memory issues. Building grand architectures which doesn't give us any value is just asking for more problems. I can elaborate more on the disadvantages of using streams here if you are still not convinced.

2022-05-17 03:23 UTC, merged